codeCSV = [
{ id: "src"},
{ id: "src.inputmask"},
{ id: "src.inputmask.RxInputMask",value: 604},
{ id: "src.index",value: 69},
{ id: "src.MultiMask",value: 46},
{ id: "src.etest"},
{ id: "src.etest.aindexSpec",value: 486},
{ id: "src.etest.aregexp-parserSpec",value: 335},
{ id: "src.etest.arxinputmaskSpec",value: 419},
{ id: "src.etest.asimpleRegExSpec",value: 162},
{ id: "src.etest.autilsSpec",value: 200},
{ id: "src.incr-regex-v3",value: 564},
{ id: "src.regexp-parser",value: 438},
{ id: "src.RxMatcher",value: 241},
{ id: "src.rxprint",value: 92},
{ id: "src.rxtree",value: 420},
{ id: "src.test"},
{ id: "src.test.indexSpec",value: 586},
{ id: "src.test.regexp-parserSpec",value: 235},
{ id: "src.test.rxinputmaskSpec",value: 559},
{ id: "src.test.simpleRegExSpec",value: 162},
{ id: "src.test.utilsSpec",value: 180},
{ id: "src.testideas",value: 214},
{ id: "src.utils",value: 291}
];