//word-split.js
// Comprehensive word mapping from popular children's stories (500-600 words)
// Split pattern: onset-rime, blend-rime, syllable-based, or whole word for sight words


const w_sight_words = {
    // ===== SIGHT WORDS & HIGH FREQUENCY (mostly whole) =====
    'the': 'the', 'and': 'and', 'you': 'you', 'for': 'for', 'are': 'are',
    'said': 'said', 'says': 'says', 'say': 'say', 'look': 'look', 'see': 'see',
    'saw': 'saw', 'seen': 'seen', 'come': 'come', 'came': 'came', 'here': 'here',
    'there': 'there', 'where': 'where', 'what': 'what', 'when': 'when', 'why': 'why',
    'which': 'which', 'this': 'this', 'that': 'that', 'these': 'these', 'those': 'those',
    'they': 'they', 'them': 'them', 'their': 'their', 'with': 'with', 'from': 'from',
    'have': 'have', 'has': 'has', 'had': 'had', 'do': 'do', 'does': 'does',
    'did': 'did', 'will': 'will', 'would': 'would', 'could': 'could', 'should': 'should',
    'his': 'his', 'her': 'her', 'him': 'him', 'he': 'he', 'she': 'she',
    'we': 'we', 'me': 'me', 'my': 'my', 'your': 'your', 'mine': 'mine',
    'yours': 'yours', 'its': 'its', "it's": "it's", 'was': 'was', 'were': 'were',
    'be': 'be', 'been': 'been', 'being': 'being', 'am': 'am', 'is': 'is',
    'to': 'to', 'too': 'too', 'two': 'two', 'by': 'by', 'bye': 'bye',
    'of': 'of', 'if': 'if', 'or': 'or', 'as': 'as', 'at': 'at',
    'an': 'an', 'a': 'a', 'i': 'i', 'in': 'in', 'on': 'on',
    'up': 'up', 'us': 'us', 'out': 'out', 'off': 'off', 'all': 'all',
    'but': 'but', 'not': 'not', 'now': 'now', 'new': 'new', 'no': 'no',
    'yes': 'yes', 'go': 'go', 'goes': 'goes', 'going': 'go-ing', 'went': 'went',
    'come': 'come', 'comes': 'comes', 'came': 'came', 'get': 'get', 'gets': 'gets',
    'got': 'got', 'gotten': 'got-ten', 'make': 'make', 'makes': 'makes', 'made': 'made',
    'take': 'take', 'takes': 'takes', 'took': 'took', 'can': 'can', 'cannot': 'can-not',
    'couldnt': 'could-not', 'wouldnt': 'would-not', 'shouldnt': 'should-not', 'dont': 'do-nt',
    'didnt': 'did-nt', 'isnt': 'is-nt', 'wasnt': 'was-nt', 'wont': 'wont', 'cant': 'cant',
    'lets': 'lets', 'thats': 'thats', 'whats': 'whats', 'wheres': 'wheres', 'whens': 'whens',
    'whos': 'whos', 'whom': 'whom', 'whose': 'whose',
};    
    // ===== CVC WORDS - ONSET/RIME =====
const w_cvc_words = {
    'cat': 'c-at', 'hat': 'h-at', 'mat': 'm-at', 'bat': 'b-at', 'rat': 'r-at',
    'sat': 's-at', 'fat': 'f-at', 'pat': 'p-at', 'vat': 'v-at', 'cab': 'c-ab',
    'lab': 'l-ab', 'tab': 't-ab', 'jab': 'j-ab', 'bag': 'b-ag', 'rag': 'r-ag',
    'tag': 't-ag', 'wag': 'w-ag', 'gag': 'g-ag', 'ham': 'h-am', 'jam': 'j-am',
    'ram': 'r-am', 'yam': 'y-am', 'bam': 'b-am', 'dam': 'd-am', 'bad': 'b-ad',
    'dad': 'd-ad', 'had': 'h-ad', 'lad': 'l-ad', 'mad': 'm-ad', 'sad': 's-ad',
    'pad': 'p-ad', 'cap': 'c-ap', 'gap': 'g-ap', 'lap': 'l-ap', 'map': 'm-ap',
    'nap': 'n-ap', 'rap': 'r-ap', 'sap': 's-ap', 'tap': 't-ap', 'zap': 'z-ap',
    'yap': 'y-ap', 'bed': 'b-ed', 'fed': 'f-ed', 'led': 'l-ed', 'red': 'r-ed',
    'wed': 'w-ed', 'beg': 'b-eg', 'leg': 'l-eg', 'peg': 'p-eg', 'hen': 'h-en',
    'men': 'm-en', 'pen': 'p-en', 'ten': 't-en', 'den': 'd-en', 'bet': 'b-et',
    'get': 'g-et', 'jet': 'j-et', 'let': 'l-et', 'met': 'm-et', 'net': 'n-et',
    'pet': 'p-et', 'set': 's-et', 'vet': 'v-et', 'wet': 'w-et', 'yet': 'y-et',
    'bin': 'b-in', 'din': 'd-in', 'fin': 'f-in', 'pin': 'p-in', 'sin': 's-in',
    'tin': 't-in', 'win': 'w-in', 'bit': 'b-it', 'fit': 'f-it', 'hit': 'h-it',
    'kit': 'k-it', 'lit': 'l-it', 'pit': 'p-it', 'sit': 's-it', 'wig': 'w-ig',
    'big': 'b-ig', 'dig': 'd-ig', 'fig': 'f-ig', 'gig': 'g-ig', 'jig': 'j-ig',
    'pig': 'p-ig', 'rig': 'r-ig', 'zig': 'z-ig', 'dip': 'd-ip', 'hip': 'h-ip',
    'lip': 'l-ip', 'nip': 'n-ip', 'rip': 'r-ip', 'sip': 's-ip', 'tip': 't-ip',
    'zip': 'z-ip', 'dip': 'd-ip', 'dim': 'd-im', 'him': 'h-im', 'rim': 'r-im',
    'brim': 'br-im', 'trim': 'tr-im', 'grim': 'gr-im', 'dog': 'd-og', 'fog': 'f-og',
    'hog': 'h-og', 'jog': 'j-og', 'log': 'l-og', 'cog': 'c-og', 'hot': 'h-ot',
    'dot': 'd-ot', 'got': 'g-ot', 'jot': 'j-ot', 'lot': 'l-ot', 'not': 'n-ot',
    'pot': 'p-ot', 'rot': 'r-ot', 'tot': 't-ot', 'hop': 'h-op', 'mop': 'm-op',
    'pop': 'p-op', 'top': 't-op', 'cop': 'c-op', 'bop': 'b-op', 'bus': 'b-us',
    'us': 'us', 'gus': 'g-us', 'bug': 'b-ug', 'dug': 'd-ug', 'hug': 'h-ug',
    'jug': 'j-ug', 'mug': 'm-ug', 'rug': 'r-ug', 'tug': 't-ug', 'pug': 'p-ug',
    'run': 'r-un', 'bun': 'b-un', 'nun': 'n-un', 'fun': 'f-un', 'gun': 'g-un',
    'sun': 's-un', 'tub': 't-ub', 'cub': 'c-ub', 'hub': 'h-ub', 'rub': 'r-ub',
    'sub': 's-ub', 'cub': 'c-ub', 'mud': 'm-ud', 'bud': 'b-ud', 'cud': 'c-ud',
};    
    // ===== BLENDS & DIGRAPHS - KEEP TOGETHER =====
const w_blends_digraphs = {
    'black': 'black', 'blue': 'blue', 'brown': 'brown', 'clap': 'cl-ap', 'clip': 'cl-ip',
    'club': 'club', 'clock': 'clock', 'cloud': 'cloud', 'clown': 'cl-own', 'drip': 'dr-ip',
    'drop': 'dr-op', 'drum': 'dr-um', 'drank': 'drank', 'dress': 'dress', 'flag': 'fl-ag',
    'flip': 'fl-ip', 'flop': 'fl-op', 'fish': 'fish', 'flash': 'flash', 'flat': 'fl-at',
    'frog': 'fr-og', 'from': 'from', 'fresh': 'fresh', 'glad': 'gl-ad', 'gloss': 'gloss',
    'glass': 'glass', 'globe': 'globe', 'glow': 'glow', 'grab': 'gr-ab', 'grin': 'gr-in',
    'grip': 'grip', 'grit': 'gr-it', 'groom': 'groom', 'crept': 'crept', 'crop': 'cr-op',
    'crab': 'cr-ab', 'crack': 'crack', 'crib': 'crib', 'cry': 'cry', 'press': 'press',
    'prince': 'prince', 'princess': 'prin-cess', 'prank': 'prank', 'prim': 'prim', 'prompt': 'prompt',
    'prop': 'pr-op', 'trap': 'tr-ap', 'trip': 'tr-ip', 'trot': 'tr-ot', 'truck': 'tr-uck',
    'track': 'track', 'trunk': 'trunk', 'trust': 'trust', 'twig': 'tw-ig', 'twin': 'twin',
    'twist': 'twist', 'slam': 'sl-am', 'slap': 'sl-ap', 'slip': 'sl-ip', 'slop': 'sl-op',
    'slot': 'sl-ot', 'smog': 'sm-og', 'smug': 'sm-ug', 'snip': 'sn-ip', 'snap': 'sn-ap',
    'snug': 'sn-ug', 'spin': 'sp-in', 'spot': 'sp-ot', 'spun': 'sp-un', 'spill': 'spill',
    'step': 'st-ep', 'stop': 'st-op', 'stir': 'stir', 'stick': 'stick', 'stack': 'stack',
    'swam': 'sw-am', 'swan': 'sw-an', 'swim': 'sw-im', 'swing': 'sw-ing', 'swung': 'sw-ung',
    'scam': 'sc-am', 'scan': 'scan', 'scat': 'sc-at', 'scuff': 'scuff', 'scuff': 'scuff',
    'skate': 'sk-ate', 'skit': 'sk-it', 'skill': 'skill', 'skin': 'skin', 'skip': 'sk-ip',
    'shut': 'shut', 'ship': 'sh-ip', 'shop': 'sh-op', 'shot': 'sh-ot', 'shot': 'sh-ot',
    'shell': 'shell', 'shift': 'shift', 'shock': 'shock', 'shook': 'shook', 'shoot': 'shoot',
    'shape': 'sh-ape', 'shark': 'shark', 'sharp': 'sharp', 'shave': 'shave', 'shift': 'shift',
    'shine': 'sh-ine', 'shiny': 'shin-y', 'shout': 'sh-out', 'thick': 'thick', 'thump': 'thump',
    'thing': 'thing', 'think': 'think', 'thin': 'thin', 'this': 'this', 'that': 'that',
    'them': 'them', 'then': 'then', 'when': 'when', 'whip': 'wh-ip', 'whale': 'wh-ale',
    'wheat': 'wheat', 'wheel': 'wheel', 'whee': 'whee', 'wheeze': 'wheeze', 'wheezy': 'wheezy',
    'wheeze': 'wheeze', 'which': 'which', 'while': 'while', 'whine': 'wh-ine', 'whimper': 'whim-per',
    'whisper': 'whis-per', 'white': 'white', 'whoop': 'whoop', 'whoosh': 'whoosh',
};    
    // ===== LONG VOWELS & VOWEL TEAMS =====
const w_long_vowels = {
    'cake': 'c-ake', 'bake': 'b-ake', 'make': 'make', 'take': 't-ake', 'wake': 'w-ake',
    'rake': 'r-ake', 'lake': 'l-ake', 'fake': 'fake', 'shake': 'shake', 'snake': 'sn-ake',
    'brake': 'br-ake', 'flake': 'flake', 'frame': 'fr-ame', 'game': 'g-ame', 'name': 'n-ame',
    'same': 's-ame', 'tame': 't-ame', 'blame': 'bl-ame', 'came': 'c-ame', 'fame': 'f-ame',
    'cave': 'c-ave', 'gave': 'g-ave', 'have': 'have', 'save': 's-ave', 'wave': 'w-ave',
    'brave': 'br-ave', 'crave': 'cr-ave', 'behave': 'be-have', 'shave': 'shave',
    'bike': 'b-ike', 'dike': 'd-ike', 'hike': 'h-ike', 'like': 'like', 'mike': 'm-ike',
    'pike': 'p-ike', 'spike': 'sp-ike', 'strike': 'strike', 'trike': 'tr-ike',
    'file': 'f-ile', 'mile': 'm-ile', 'pile': 'p-ile', 'smile': 'sm-ile', 'while': 'while',
    'tile': 't-ile', 'kite': 'k-ite', 'bite': 'b-ite', 'quite': 'quite', 'white': 'white',
    'quite': 'quite', 'write': 'wr-ite', 'quite': 'quite', 'site': 's-ite', 'kite': 'k-ite',
    'dive': 'd-ive', 'five': 'f-ive', 'hive': 'h-ive', 'live': 'live', 'drive': 'dr-ive',
    'chive': 'ch-ive', 'jive': 'j-ive', 'thrive': 'thrive', 'tribe': 'tr-ibe', 'dime': 'd-ime',
    'lime': 'l-ime', 'time': 't-ime', 'chime': 'ch-ime', 'crime': 'cr-ime', 'prime': 'prime',
    'bride': 'br-ide', 'glide': 'gl-ide', 'hide': 'h-ide', 'ride': 'r-ide', 'side': 's-ide',
    'slide': 'sl-ide', 'tide': 't-ide', 'wide': 'w-ide', 'pride': 'pride', 'smile': 'sm-ile',
    'home': 'home', 'bone': 'b-one', 'cone': 'c-one', 'phone': 'phone', 'stone': 'stone',
    'alone': 'a-lone', 'throne': 'thr-one', 'globe': 'globe', 'robe': 'r-obe', 'dope': 'd-ope',
    'grope': 'grope', 'hope': 'h-ope', 'rope': 'r-ope', 'mope': 'm-ope', 'scope': 'scope',
    'stole': 'st-ole', 'toll': 't-oll', 'roll': 'r-oll', 'troll': 'troll', 'scroll': 'scroll',
    'hole': 'h-ole', 'mole': 'm-ole', 'pole': 'p-ole', 'sole': 'sole', 'stole': 'st-ole',
    'vote': 'v-ote', 'note': 'n-ote', 'quote': 'quote', 'smote': 'smote', 'remote': 're-mote',
    'cute': 'c-ute', 'mute': 'm-ute', 'brute': 'br-ute', 'flute': 'fl-ute', 'plume': 'pl-ume',
    'prune': 'pr-une', 'rule': 'r-ule', 'rude': 'r-ude', 'crude': 'cr-ude', 'prude': 'prude',
};    
    // Vowel teams
const w_vowel_teams = {
    'boat': 'b-oa-t', 'goat': 'g-oa-t', 'coat': 'c-oa-t', 'float': 'fl-oa-t', 'soap': 's-oa-p',
    'road': 'r-oa-d', 'toad': 't-oa-d', 'foal': 'f-oa-l', 'coal': 'c-oa-l', 'goal': 'g-oa-l',
    'loaf': 'l-oa-f', 'oak': 'o-ak', 'soak': 's-oa-k', 'soap': 's-oa-p', 'throat': 'thr-oa-t',
    'rain': 'r-ai-n', 'pain': 'p-ai-n', 'gain': 'g-ai-n', 'chain': 'ch-ain', 'brain': 'br-ain',
    'drain': 'dr-ain', 'grain': 'gr-ain', 'plain': 'pl-ain', 'paint': 'p-aint', 'faint': 'f-aint',
    'acorn': 'a-corn', 'apron': 'a-pron', 'agent': 'a-gent', 'basil': 'bas-il', 'caper': 'c-aper',
    'fatal': 'f-atal', 'labored': 'la-bored', 'table': 't-able', 'radar': 'ra-dar', 'total': 'to-tal',
    'meat': 'm-ea-t', 'seat': 's-ea-t', 'beat': 'b-ea-t', 'cheat': 'ch-eat', 'heat': 'h-ea-t',
    'neat': 'n-ea-t', 'read': 'read', 'treat': 't-reat', 'bead': 'b-ea-d', 'lead': 'lead',
    'plead': 'pl-ead', 'steam': 'st-eam', 'cream': 'cr-eam', 'dream': 'dr-eam', 'gleam': 'gl-eam',
    'beach': 'b-each', 'peach': 'p-each', 'teach': 't-each', 'reach': 'r-each', 'seal': 's-eal',
    'meal': 'm-eal', 'real': 'real', 'teal': 't-eal', 'beam': 'b-eam', 'seam': 's-eam',
    'team': 't-eam', 'lean': 'l-ean', 'mean': 'm-ean', 'clean': 'cl-ean', 'grean': 'gr-ean',
    'see': 'see', 'seed': 's-eed', 'seem': 's-eem', 'seen': 's-een', 'seek': 's-eek',
    'peel': 'p-eel', 'feel': 'f-eel', 'heel': 'h-eel', 'wheel': 'wheel', 'three': 'thr-ee',
    'tree': 'tr-ee', 'free': 'fr-ee', 'flea': 'fl-ea', 'weak': 'w-eak', 'peak': 'p-eak',
    'speak': 'sp-eak', 'beet': 'b-eet', 'feet': 'f-eet', 'meet': 'm-eet', 'sweet': 'sw-eet',
    'sleep': 'sl-eep', 'sheep': 'sh-eep', 'creep': 'cr-eep', 'green': 'gr-een', 'queen': 'qu-een',
    'screen': 'scr-een', 'street': 'str-eet', 'pie': 'p-ie', 'tie': 't-ie', 'lie': 'l-ie',
    'die': 'd-ie', 'fried': 'fr-ied', 'tried': 'tr-ied', 'cried': 'cr-ied', 'pried': 'pr-ied',
    'spied': 'sp-ied', 'field': 'f-ield', 'yield': 'y-ield', 'chief': 'ch-ief', 'thief': 'th-ief',
    'piece': 'p-iece', 'niece': 'n-iece', 'believe': 'be-lieve', 'achieve': 'a-chieve',
    'high': 'high', 'light': 'l-ight', 'night': 'n-ight', 'right': 'r-ight', 'sight': 's-ight',
    'tight': 't-ight', 'fight': 'f-ight', 'might': 'm-ight', 'bright': 'br-ight', 'fright': 'fr-ight',
    'knight': 'knight', 'sigh': 's-igh', 'sign': 's-ign', 'blow': 'bl-ow', 'slow': 'sl-ow',
    'low': 'low', 'crow': 'cr-ow', 'grow': 'gr-ow', 'show': 'sh-ow', 'snow': 'sn-ow',
    'stow': 'st-ow', 'throw': 'thr-ow', 'tow': 't-ow', 'flow': 'fl-ow', 'glow': 'gl-ow',
    'know': 'know', 'bellow': 'bel-low', 'yellow': 'y-el-low', 'mellow': 'mel-low',
    'fellow': 'fel-low', 'follow': 'fol-low', 'hollow': 'hol-low', 'pillow': 'pil-low',
    'window': 'win-dow', 'shadow': 'sh-ad-ow', 'crown': 'cr-own', 'brown': 'brown', 'clown': 'cl-own',
    'down': 'down', 'drown': 'dr-own', 'town': 't-own', 'gown': 'g-own', 'frown': 'fr-own',
    'ruin': 'r-u-in', 'fruit': 'fr-uit', 'suit': 's-uit', 'juice': 'j-uice', 'bruise': 'br-uise',
    'sluice': 'sl-uice', 'yule': 'y-ule', 'tune': 't-une', 'prune': 'pr-une', 'rune': 'r-une',
    'June': 'J-une', 'few': 'f-ew', 'new': 'n-ew', 'grew': 'gr-ew', 'blew': 'bl-ew',
    'drew': 'dr-ew', 'stew': 'st-ew', 'threw': 'thr-ew', 'screw': 'scr-ew', 'chew': 'ch-ew',
    'shoe': 'sh-oe', 'canoe': 'can-oe', 'tomato': 'to-ma-to', 'potato': 'po-ta-to',
    'tornado': 'tor-na-do', 'zero': 'z-er-o', 'hero': 'h-er-o', 'cargo': 'car-go', 'mango': 'm-an-go',
};    
    // ===== R-CONTROLLED VOWELS =====
const w_r_controlled_vowels = {
    'car': 'car', 'bar': 'bar', 'far': 'far', 'jar': 'jar', 'tar': 'tar',
    'star': 'star', 'scar': 'scar', 'char': 'char', 'park': 'park', 'bark': 'bark',
    'dark': 'dark', 'mark': 'mark', 'shark': 'shark', 'spark': 'spark', 'farm': 'farm',
    'harm': 'harm', 'charm': 'charm', 'arm': 'arm', 'barn': 'barn', 'yarn': 'yarn',
    'hard': 'hard', 'card': 'card', 'guard': 'guard', 'yard': 'yard', 'her': 'her',
    'verb': 'verb', 'herd': 'herd', 'perch': 'perch', 'fern': 'fern', 'germ': 'germ',
    'herb': 'herb', 'term': 'term', 'serve': 'serve', 'herd': 'herd', 'perk': 'perk',
    'per': 'per', 'perm': 'perm', 'bird': 'bird', 'dirt': 'dirt', 'girl': 'girl',
    'sir': 'sir', 'stir': 'stir', 'third': 'third', 'first': 'first', 'shirt': 'shirt',
    'skirt': 'skirt', 'squirt': 'squirt', 'thirst': 'thirst', 'birth': 'birth',
    'chirp': 'chirp', 'circus': 'cir-cus', 'fir': 'fir', 'fir': 'fir', 'fur': 'fur',
    'burn': 'burn', 'turn': 'turn', 'spur': 'spur', 'turkey': 'tur-key', 'turtle': 'tur-tle',
    'urchin': 'ur-chin', 'curl': 'curl', 'hurl': 'hurl', 'nurse': 'nurse', 'purse': 'purse',
    'curse': 'curse', 'fur': 'fur', 'blur': 'blur', 'slur': 'slur', 'for': 'for',
    'fort': 'fort', 'fork': 'fork', 'corn': 'corn', 'horn': 'horn', 'thorn': 'thorn',
    'born': 'born', 'torn': 'torn', 'worn': 'worn', 'pork': 'pork', 'stork': 'stork',
    'cord': 'cord', 'lord': 'lord', 'ford': 'ford', 'short': 'short', 'sport': 'sport',
    'north': 'north', 'morn': 'morn', 'nor': 'nor', 'core': 'c-ore', 'bore': 'b-ore',
    'more': 'more', 'sore': 's-ore', 'tore': 't-ore', 'wore': 'w-ore', 'store': 'st-ore',
    'horse': 'horse', 'course': 'c-ourse', 'four': 'four', 'pour': 'p-our', 'tour': 't-our',
    'court': 'court', 'your': 'your', 'cheer': 'ch-eer', 'steer': 'st-eer', 'deer': 'd-eer',
    'peer': 'p-eer', 'veer': 'v-eer', 'here': 'here', 'mere': 'm-ere', 'sincere': 'sin-cere',
};    
    // ===== MULTISYLLABIC WORDS - SYLLABLE SPLIT =====
const w_multisyllabic_split = {
    'little': 'lit-tle', 'middle': 'mid-dle', 'cuddle': 'cud-dle', 'puddle': 'pud-dle',
    'riddle': 'rid-dle', 'peddle': 'ped-dle', 'fiddle': 'fid-dle', 'twinkle': 'tw-ink-le',
    'sprinkle': 'spr-ink-le', 'wrinkle': 'wr-ink-le', 'tinkle': 'tink-le', 'crinkle': 'cr-ink-le',
    'sprinkle': 'sprinkle', 'sparkle': 'spar-kle', 'bicycle': 'bi-cy-cle', 'tricycle': 'tri-cy-cle',
    'recycle': 're-cy-cle', 'uncle': 'un-cle', 'candle': 'can-dle', 'handle': 'han-dle',
    'bundle': 'bun-dle', 'wobble': 'wob-ble', 'bubble': 'bub-ble', 'hobble': 'hob-ble',
    'nibble': 'nib-ble', 'scramble': 'scram-ble', 'humble': 'hum-ble', 'rumble': 'rum-ble',
    'stumble': 'stum-ble', 'hundred': 'hun-dred', 'thunder': 'thun-der', 'wonder': 'won-der',
    'plunder': 'plun-der', 'under': 'un-der', 'monster': 'mon-ster', 'rooster': 'roos-ter',
    'booster': 'boost-er', 'yesterday': 'yes-ter-day', 'tomorrow': 'to-mor-row',
    'today': 'to-day', 'together': 'to-geth-er', 'forever': 'for-ev-er', 'another': 'a-noth-er',
    'other': 'oth-er', 'mother': 'moth-er', 'father': 'fath-er', 'brother': 'broth-er',
    'sister': 'sis-ter', 'grandmother': 'grand-moth-er', 'grandfather': 'grand-fath-er',
    'grandparent': 'grand-par-ent', 'parent': 'par-ent', 'daughter': 'daugh-ter', 'auntie': 'aunt-ie',
    'uncle': 'un-cle', 'cousin': 'cous-in', 'family': 'fam-i-ly', 'people': 'peo-ple',
    'children': 'chil-dren', 'child': 'child', 'baby': 'ba-by', 'infant': 'in-fant', 'toddler': 'tod-dler',
    'kitten': 'kit-ten', 'puppy': 'pup-py', 'bunny': 'bun-ny', 'pony': 'po-ny', 'chicken': 'chick-en',
    'turkey': 'tur-key', 'robin': 'rob-in', 'pigeon': 'pig-eon', 'spider': 'spi-der', 'lizard': 'liz-ard',
    'caterpillar': 'cat-er-pil-lar', 'butterfly': 'but-ter-fly', 'dragonfly': 'drag-on-fly',
    'butter': 'but-ter', 'flutter': 'flut-ter', 'clutter': 'clut-ter', 'better': 'bet-ter',
    'letter': 'let-ter', 'batter': 'batt-er', 'matter': 'matt-er', 'pattern': 'patt-ern',
    'pattern': 'patt-ern', 'potter': 'pott-er', 'water': 'wa-ter', 'matter': 'matt-er',
    'shatter': 'shatt-er', 'latter': 'latt-er', 'splatter': 'splat-ter', 'scatter': 'scatt-er',
    'flatter': 'flatt-er', 'battery': 'batt-er-y', 'lottery': 'lott-er-y', 'shivery': 'shiv-er-y',
    'quiver': 'quiv-er', 'silver': 'silv-er', 'liver': 'liv-er', 'river': 'riv-er', 'fever': 'fev-er',
    'never': 'nev-er', 'ever': 'ev-er', 'forever': 'for-ev-er', 'sever': 'sev-er', 'clever': 'clev-er',
    'whomever': 'who-mev-er', 'whatever': 'what-ev-er', 'whenever': 'when-ev-er', 'wherever': 'where-ev-er',
    'however': 'how-ev-er', 'whatever': 'what-ev-er', 'forever': 'for-ev-er', 'shovel': 'shov-el',
    'level': 'lev-el', 'hovel': 'hov-el', 'novel': 'nov-el', 'travel': 'trav-el', 'camel': 'cam-el',
    'tunnel': 'tun-nel', 'channel': 'chan-nel', 'flannel': 'flan-nel', 'funnel': 'fun-nel',
    'kennel': 'ken-nel', 'person': 'per-son', 'pigeon': 'pig-eon', 'lesson': 'less-on', 'lessen': 'less-en',
    'season': 'sea-son', 'reason': 'rea-son', 'treason': 'trea-son', 'beacon': 'bea-con', 'deacon': 'dea-con',
    'dragon': 'drag-on', 'wagon': 'wag-on', 'flagoon': 'fla-goon', 'balloon': 'bal-loon', 'saloon': 'sa-loon',
    'spittoon': 'spit-toon', 'afternoon': 'af-ter-noon', 'noon': 'noon', 'moon': 'moon', 'spoon': 'sp-oon',
    'cartoon': 'car-toon', 'baboon': 'ba-boon', 'raccoon': 'rac-coon', 'festoon': 'fes-toon', 'pattern': 'patt-ern',
    'better': 'bet-ter', 'butter': 'but-ter', 'bitter': 'bitt-er', 'utterly': 'ut-ter-ly', 'utter': 'utt-er',
    'mutter': 'mutt-er', 'stutter': 'stutt-er', 'flutter': 'flutt-er', 'shutter': 'shutt-er', 'shudder': 'shudd-er',
    'rudder': 'rudd-er', 'fodder': 'fodd-er', 'plodder': 'plodd-er', 'podder': 'podd-er', 'toddle': 'todd-le',
    'coddle': 'codd-le', 'model': 'mod-el', 'yodel': 'yod-el', 'today': 'to-day', 'tonight': 'to-night',
    'tomorrow': 'to-mor-row', 'together': 'to-geth-er', 'forever': 'for-ev-er', 'another': 'a-noth-er',
    'other': 'oth-er', 'mother': 'moth-er', 'father': 'fath-er', 'brother': 'broth-er', 'sister': 'sis-ter',
    'grandmother': 'grand-moth-er', 'grandfather': 'grand-fath-er', 'grandparent': 'grand-par-ent',
    'parent': 'par-ent', 'daughter': 'daugh-ter', 'auntie': 'aunt-ie', 'uncle': 'un-cle', 'cousin': 'cous-in',
    'family': 'fam-i-ly', 'people': 'peo-ple', 'children': 'chil-dren', 'child': 'child', 'baby': 'ba-by',
    'infant': 'in-fant', 'toddler': 'tod-dler', 'kitten': 'kit-ten', 'puppy': 'pup-py', 'bunny': 'bun-ny',
    'pony': 'po-ny', 'chicken': 'chick-en', 'turkey': 'tur-key', 'robin': 'rob-in', 'pigeon': 'pig-eon',
    'spider': 'spi-der', 'lizard': 'liz-ard', 'caterpillar': 'cat-er-pil-lar', 'butterfly': 'but-ter-fly',
    'dragonfly': 'drag-on-fly', 'butter': 'but-ter', 'flutter': 'flut-ter', 'clutter': 'clut-ter',
    'better': 'bet-ter', 'letter': 'let-ter', 'batter': 'batt-er', 'matter': 'matt-er', 'pattern': 'patt-ern',
    'pattern': 'patt-ern', 'potter': 'pott-er', 'water': 'wa-ter', 'shatter': 'shatt-er', 'latter': 'latt-er',
    'splatter': 'splat-ter', 'scatter': 'scatt-er', 'flatter': 'flatt-er', 'battery': 'batt-er-y',
    'lottery': 'lott-er-y', 'shivery': 'shiv-er-y', 'quiver': 'quiv-er', 'silver': 'silv-er', 'liver': 'liv-er',
    'river': 'riv-er', 'fever': 'fev-er', 'never': 'nev-er', 'ever': 'ev-er', 'forever': 'for-ev-er',
    'sever': 'sev-er', 'clever': 'clev-er', 'whomever': 'who-mev-er', 'whatever': 'what-ev-er',
    'whenever': 'when-ev-er', 'wherever': 'where-ev-er', 'however': 'how-ev-er', 'whatever': 'what-ev-er',
    'shovel': 'shov-el', 'level': 'lev-el', 'hovel': 'hov-el', 'novel': 'nov-el', 'travel': 'trav-el',
    'camel': 'cam-el', 'tunnel': 'tun-nel', 'channel': 'chan-nel', 'flannel': 'flan-nel', 'funnel': 'fun-nel',
    'kannel': 'ken-nel', 'person': 'per-son', 'pigeon': 'pig-eon', 'lesson': 'less-on', 'lessen': 'less-en',
    'season': 'sea-son', 'reason': 'rea-son', 'treason': 'trea-son', 'beacon': 'bea-con', 'deacon': 'dea-con',
    'dragon': 'drag-on', 'wagon': 'wag-on', 'balloon': 'bal-loon', 'saloon': 'sa-loon', 'spittoon': 'spit-toon',
    'afternoon': 'af-ter-noon', 'noon': 'noon', 'moon': 'moon', 'spoon': 'sp-oon', 'cartoon': 'car-toon',
    'baboon': 'ba-boon', 'raccoon': 'rac-coon', 'festoon': 'fes-toon', 'pattern': 'patt-ern', 'better': 'bet-ter',
    'butter': 'but-ter', 'bitter': 'bitt-er', 'utterly': 'ut-ter-ly', 'utter': 'utt-er', 'mutter': 'mutt-er',
    'stutter': 'stutt-er', 'flutter': 'flutt-er', 'shutter': 'shutt-er', 'shudder': 'shudd-er', 'rudder': 'rudd-er',
    'fodder': 'fodd-er', 'plodder': 'plodd-er', 'podder': 'podd-er', 'toddle': 'todd-le', 'coddle': 'codd-le',
    'model': 'mod-el', 'yodel': 'yod-el', 'today': 'to-day', 'tonight': 'to-night', 'tomorrow': 'to-mor-row',
    'together': 'to-geth-er', 'forever': 'for-ev-er', 'another': 'a-noth-er', 'other': 'oth-er',
};    
    // ===== ANIMALS FROM STORIES =====
const w_animals = {
    'bear': 'bear', 'panda': 'pan-da', 'koala': 'ko-a-la', 'grizzly': 'griz-zly', 'polar': 'po-lar',
    'bear': 'bear', 'bird': 'b-ir-d', 'robin': 'rob-in', 'sparrow': 'spar-row', 'eagle': 'ea-gle',
    'hawk': 'hawk', 'falcon': 'fal-con', 'owl': 'owl', 'swan': 'swan', 'duck': 'd-uck',
    'mallard': 'mal-lard', 'goose': 'goo-se', 'chick': 'chick', 'duckling': 'duck-ling', 'gosling': 'gos-ling',
    'chicken': 'chick-en', 'rooster': 'roost-er', 'hen': 'h-en', 'turkey': 'tur-key', 'pigeon': 'pig-eon',
    'dove': 'd-ove', 'fish': 'fish', 'goldfish': 'gold-fish', 'shark': 'shark', 'whale': 'wh-ale',
    'dolphin': 'dol-phin', 'porpoise': 'por-poise', 'seal': 's-eal', 'walrus': 'wal-rus', 'otter': 'ott-er',
    'frog': 'fr-og', 'toad': 't-oad', 'tadpole': 'tad-pole', 'newt': 'newt', 'salamander': 'sal-a-man-der',
    'lizard': 'liz-ard', 'gecko': 'gec-ko', 'iguana': 'i-gua-na', 'chameleon': 'cha-me-le-on',
    'snake': 'sn-ake', 'python': 'py-thon', 'cobra': 'co-bra', 'rattle': 'ratt-le', 'snake': 'sn-ake',
    'turtle': 'tur-tle', 'tortoise': 'tor-toise', 'terrapin': 'ter-ra-pin', 'crocodile': 'croc-o-dile',
    'alligator': 'al-li-ga-tor', 'dinosaur': 'di-no-saur', 'rex': 'rex', 'brontosaurus': 'bron-to-saur-us',
    'stegosaurus': 'steg-o-saur-us', 'triceratops': 'tri-cer-a-tops', 'pterodactyl': 'pter-o-dac-tyl',
    'hamster': 'ham-ster', 'gerbil': 'ger-bil', 'mouse': 'm-ou-se', 'mice': 'm-ice', 'rat': 'r-at',
    'rabbit': 'rab-bit', 'hare': 'h-are', 'bunny': 'bun-ny', 'guinea': 'guin-ea', 'pig': 'pig',
    'cavy': 'cav-y', 'hedgehog': 'hedge-hog', 'porcupine': 'por-cu-pine', 'bat': 'b-at', 'flying': 'fly-ing',
    'fox': 'fox', 'wolf': 'wolf', 'wolves': 'wolves', 'coyote': 'coy-ote', 'dingo': 'din-go',
    'hyena': 'hy-e-na', 'lion': 'l-i-on', 'tiger': 't-i-ger', 'leopard': 'leop-ard', 'panther': 'pan-ther',
    'jaguar': 'jag-u-ar', 'cheetah': 'chee-tah', 'cougar': 'cou-gar', 'puma': 'pu-ma', 'lynx': 'lynx',
    'bobcat': 'bob-cat', 'cat': 'c-at', 'kitten': 'kit-ten', 'tomcat': 'tom-cat', 'ocelot': 'oc-e-lot',
    'serval': 'ser-val', 'elephant': 'el-e-phant', 'mammoth': 'mam-moth', 'hippopotamus': 'hip-po-pot-a-mus',
    'rhinoceros': 'rhi-noc-er-os', 'giraffe': 'gi-raffe', 'zebra': 'zeb-ra', 'camel': 'cam-el',
    'desert': 'des-ert', 'horse': 'h-or-se', 'pony': 'po-ny', 'donkey': 'don-key', 'mule': 'm-ule',
    'zebu': 'zeb-u', 'ox': 'ox', 'oxen': 'ox-en', 'buffalo': 'buf-fa-lo', 'bison': 'bi-son',
    'yak': 'yak', 'llama': 'lla-ma', 'alpaca': 'al-pa-ca', 'vicuña': 'vi-cu-ña', 'guanaco': 'gua-na-co',
    'sheep': 'sh-eep', 'lamb': 'l-amb', 'ram': 'r-am', 'ewe': 'ewe', 'goat': 'g-oat',
    'kid': 'kid', 'ibex': 'i-bex', 'markhor': 'mark-hor', 'monkey': 'mon-key', 'ape': 'ape',
    'gorilla': 'go-ril-la', 'chimpanzee': 'chim-pan-zee', 'orangutan': 'o-rang-u-tan', 'gibbon': 'gib-bon',
    'baboon': 'ba-boon', 'marmoset': 'mar-mo-set', 'tamarin': 'ta-ma-rin', 'lemur': 'le-mur',
    'loris': 'lor-is', 'butterfly': 'but-ter-fly', 'moth': 'm-oth', 'bee': 'b-ee', 'wasp': 'wasp',
    'hornet': 'hor-net', 'ant': 'ant', 'grasshopper': 'grass-hop-per', 'cricket': 'crick-et',
    'ladybug': 'la-dy-bug', 'beetle': 'bee-tle', 'dragonfly': 'drag-on-fly', 'firefly': 'fire-fly',
    'caterpillar': 'cat-er-pil-lar', 'worm': 'worm', 'slug': 'sl-ug', 'snail': 'sn-ail',
    'spider': 'spi-der', 'tick': 'tick', 'mite': 'mite', 'flea': 'fl-ea', 'mosquito': 'mos-qui-to',
    'fly': 'fl-y', 'butterfly': 'but-ter-fly', 'penguin': 'pen-guin', 'seagull': 'sea-gull',
    'albatross': 'al-ba-tross', 'pelican': 'pel-i-can', 'flamingo': 'fla-min-go', 'heron': 'h-er-on',
    'egret': 'e-gret', 'ibis': 'i-bis', 'stork': 'stork', 'crane': 'cr-ane', 'swan': 'swan',
    'goose': 'goo-se', 'duck': 'd-uck', 'mallard': 'mal-lard', 'pigeon': 'pig-eon', 'dove': 'd-ove',
    'crow': 'cr-ow', 'raven': 'ra-ven', 'magpie': 'mag-pie', 'jay': 'j-ay', 'parrot': 'par-rot',
    'cockatoo': 'cock-a-too', 'budgie': 'bud-gie', 'canary': 'ca-nar-y', 'finch': 'finch',
    'starling': 'star-ling', 'sparrow': 'spar-row', 'robin': 'rob-in', 'wren': 'wren',
    'thrush': 'thrush', 'blackbird': 'black-bird', 'nightingale': 'night-in-gale', 'cuckoo': 'cuck-oo',
    'kingfisher': 'king-fish-er', 'woodpecker': 'wood-peck-er', 'hummingbird': 'hum-ming-bird',
    'puffin': 'puf-fin', 'peregrine': 'per-e-grine', 'falcon': 'fal-con', 'eagle': 'ea-gle',
    'hawk': 'hawk', 'buzzard': 'buz-zard', 'vulture': 'vul-ture', 'osprey': 'os-prey', 'kite': 'k-ite',
    'harrier': 'har-ri-er', 'kestrel': 'kes-trel', 'merlin': 'mer-lin', 'goshawk': 'gos-hawk',
    'sparrowhawk': 'spar-row-hawk', 'tawny': 'taw-ny', 'owl': 'owl', 'barn': 'barn', 'eagle-owl': 'ea-gle-owl',
    'little': 'lit-tle', 'ears': 'ears', 'holes', 'holes', 'tawny': 'taw-ny', 'furry': 'fur-ry',
    'wings': 'wings', 'shriek': 'sh-riek', 'shrieked': 'sh-riek-ed', 'shrieking': 'sh-riek-ing',
};    
    // ===== FOOD FROM STORIES =====
const w_food = {
    'apple': 'ap-ple', 'pear': 'pear', 'plum': 'plum', 'strawberry': 'straw-ber-ry', 'orange': 'or-ange',
    'cake': 'c-ake', 'pickle': 'pick-le', 'cheese': 'cheese', 'salami': 'sa-la-mi', 'lollipop': 'lol-li-pop',
    'pie': 'p-ie', 'sausage': 'sau-sage', 'cherry': 'cher-ry', 'watermelon': 'wa-ter-mel-on',
    'cocoon': 'co-coon', 'leaf': 'l-eaf', 'caterpillar': 'cat-er-pil-lar', 'butterfly': 'but-ter-fly',
    'hungry': 'hung-ry', 'cocoon': 'co-coon', 'butter': 'but-ter', 'chocolate': 'choc-o-late',
    'cookie': 'cook-ie', 'muffin': 'muf-fin', 'pancake': 'pan-c-ake', 'waffle': 'waf-fle', 'bagel': 'ba-gel',
    'donut': 'do-nut', 'croissant': 'crois-sant', 'toast': 'toast', 'cereal': 'ce-re-al',
    'oatmeal': 'oat-meal', 'porridge': 'por-ridge', 'grits': 'grits', 'syrup': 'syr-up', 'honey': 'hon-ey',
    'jam': 'j-am', 'jelly': 'jel-ly', 'peanut': 'pea-nut', 'butter': 'but-ter', 'sandwich': 'sand-wich',
    'crackers': 'crack-ers', 'pretzel': 'pret-zel', 'chips': 'chips', 'popcorn': 'pop-corn', 'candy': 'can-dy',
    'gum': 'gum', 'mint': 'mint', 'soda': 'so-da', 'juice': 'j-uice', 'milk': 'milk', 'water': 'wa-ter',
    'lemonade': 'lem-on-ade', 'punch': 'punch', 'coffee': 'cof-fee', 'tea': 't-ea', 'milkshake': 'milk-shake',
    'smoothie': 'smooth-ie', 'pizza': 'piz-za', 'burger': 'burg-er', 'hotdog': 'hot-dog', 'fries': 'fr-ies',
    'salad': 'sal-ad', 'soup': 'soup', 'stew': 'st-ew', 'pasta': 'pas-ta', 'spaghetti': 'spa-ghe-tti',
    'meatball': 'meat-ball', 'chicken': 'chick-en', 'nugget': 'nug-get', 'taco': 'ta-co', 'burrito': 'bur-ri-to',
    'quesadilla': 'que-sa-dil-la', 'nachos': 'na-chos', 'salsa': 'sal-sa', 'guacamole': 'gua-ca-mo-le',
    'bean': 'b-ean', 'cheese': 'cheese', 'sour': 'sour', 'cream': 'cr-eam', 'dip': 'dip', 'vegetable': 'veg-e-ta-ble',
    'carrot': 'carr-ot', 'broccoli': 'broc-co-li', 'pepper': 'pep-per', 'cucumber': 'cu-cum-ber', 'lettuce': 'lett-uce',
    'tomato': 'to-ma-to', 'potato': 'po-ta-to', 'corn': 'corn', 'peas': 'peas', 'beans': 'beans', 'rice': 'r-ice',
    'noodle': 'noo-dle', 'bread': 'br-e-ad', 'roll': 'r-oll', 'biscuit': 'bis-cuit', 'muffin': 'muf-fin',
    'cupcake': 'cup-c-ake', 'brownie': 'brown-ie', 'pie': 'p-ie', 'tart': 't-art', 'pudding': 'pud-ding',
    'custard': 'cus-tard', 'jello': 'jel-lo', 'icecream': 'ice-cr-eam', 'sundae': 'sun-d-ae', 'sprinkles': 'sprink-les',
    'whipped': 'whip-ped', 'cream': 'cr-eam', 'caramel': 'car-a-mel', 'fudge': 'fudge', 'marshmallow': 'marsh-mal-low',
};    
    // ===== COLORS & NUMBERS =====
const w_colors = {
    'red': 'red', 'orange': 'or-ange', 'yellow': 'y-el-low', 'green': 'gr-een', 'blue': 'blue',
    'purple': 'pur-ple', 'pink': 'p-ink', 'brown': 'brown', 'black': 'black', 'white': 'white',
    'gray': 'gray', 'violet': 'vi-o-let', 'indigo': 'in-di-go', 'magenta': 'ma-gen-ta', 'cyan': 'cy-an',
    'crimson': 'crim-son', 'scarlet': 'scar-let', 'vermillion': 'ver-mil-lion', 'amber': 'am-ber',
    'chartreuse': 'char-treuse', 'jade': 'j-ade', 'emerald': 'em-er-ald', 'sapphire': 'saph-ire',
    'turquoise': 'tur-quoise', 'aquamarine': 'a-qua-ma-rine', 'periwinkle': 'per-i-wink-l-e', 'lavender': 'lav-end-er',
    'lilac': 'li-lac', 'mauve': 'mauve', 'lava': 'la-va', 'flame': 'fl-ame', 'gold': 'gold', 'silver': 'silv-er',
    'bronze': 'bronze', 'copper': 'cop-per', 'iridescent': 'ir-i-des-cent', 'rainbow': 'rain-bow', 'one': 'one',
    'two': 'two', 'three': 'three', 'four': 'four', 'five': 'f-ive', 'six': 'six', 'seven': 'sev-en',
    'eight': 'eight', 'nine': 'n-ine', 'ten': 'ten', 'eleven': 'e-lev-en', 'twelve': 'tw-elve', 'thirteen': 'th-ir-teen',
    'fourteen': 'four-teen', 'fifteen': 'fif-teen', 'sixteen': 'six-teen', 'seventeen': 'sev-en-teen',
    'eighteen': 'eight-teen', 'nineteen': 'nine-teen', 'twenty': 'twent-y', 'thirty': 'thir-ty', 'forty': 'for-ty',
    'fifty': 'fif-ty', 'sixty': 'six-ty', 'seventy': 'sev-en-ty', 'eighty': 'eight-y', 'ninety': 'nine-ty',
    'hundred': 'hun-dred', 'thousand': 'thou-sand', 'million': 'mil-lion', 'billion': 'bil-lion', 'first': 'first',
    'second': 'sec-ond', 'third': 'third', 'fourth': 'fourth', 'fifth': 'f-if-th', 'sixth': 'sixth', 'seventh': 'sev-enth',
    'eighth': 'eighth', 'ninth': 'n-ine-th', 'tenth': 'tenth',
};    
    // ===== NATURE & WEATHER =====
const w_nature = {
    'sun': 's-un', 'moon': 'moon', 'star': 'st-ar', 'cloud': 'cl-ou-d', 'rain': 'r-ai-n', 'bow': 'b-ow',
    'rainbow': 'rain-bow', 'storm': 'st-orm', 'lightning': 'light-ning', 'thunder': 'thun-der', 'wind': 'w- i-nd',
    'breeze': 'br-ee-ze', 'gale': 'g-ale', 'hurricane': 'hur-ri-cane', 'tornado': 'tor-na-do', 'flood': 'fl-oo-d',
    'earthquake': 'earth-quake', 'volcano': 'vol-ca-no', 'eruption': 'e-rup-tion', 'lava': 'la-va', 'ash': 'ash',
    'smoke': 'sm-oke', 'fire': 'f-ire', 'flame': 'fl-ame', 'spark': 'spark', 'ember': 'em-ber',
    'forest': 'for-est', 'woods': 'w-oo-d-s', 'jungle': 'jun-gle', 'meadow': 'mead-ow', 'field': 'f-ield',
    'prairie': 'prair-ie', 'savanna': 'sa-van-na', 'desert': 'des-ert', 'tundra': 'tun-dra', 'taiga': 'tai-ga',
    'mountain': 'moun-tain', 'hill': 'h-ill', 'valley': 'vall-ey', 'canyon': 'can-yon', 'cliff': 'cl-iff',
    'cave': 'c-ave', 'cavern': 'cav-ern', 'rock': 'r-ock', 'stone': 'st-one', 'boulder': 'boul-der',
    'pebble': 'peb-ble', 'sand': 's-and', 'dune': 'd-une', 'beach': 'b-ea-ch', 'shore': 'sh-ore',
    'coast': 'co-ast', 'bay': 'b-ay', 'gulf': 'gulf', 'sea': 's-ea', 'ocean': 'o-cean',
    'river': 'riv-er', 'stream': 'str-eam', 'brook': 'br-oo-k', 'creek': 'cr-eek', 'pond': 'p-ond',
    'lake': 'l-ake', 'reservoir': 'res-er-voir', 'dam': 'd-am', 'waterfall': 'wa-ter-fall', 'cascade': 'cas-cade',
    'plant': 'pl-ant', 'tree': 'tr-ee', 'bush': 'b-ush', 'shrub': 'shr-ub', 'flower': 'fl-ow-er',
    'grass': 'gr-ass', 'weed': 'w-eed', 'vine': 'v-ine', 'fern': 'fern', 'moss': 'm-oss',
    'algae': 'al-gae', 'lichen': 'li-chen', 'seed': 's-eed', 'sprout': 'spr-out', 'bloom': 'bl-oom',
    'petal': 'pet-al', 'leaf': 'l-eaf', 'stem': 'st-em', 'root': 'r-oot', 'branch': 'branch',
    'twig': 'tw-ig', 'bark': 'bark', 'trunk': 'trunk', 'grasshopper': 'grass-hop-per', 'caterpillar': 'cat-er-pil-lar',
    'butterfly': 'but-ter-fly', 'moth': 'm-oth', 'bee': 'b-ee', 'wasp': 'wasp', 'hornet': 'hor-net',
    'ant': 'ant', 'cricket': 'crick-et', 'ladybug': 'la-dy-bug', 'beetle': 'bee-tle', 'dragonfly': 'drag-on-fly',
    'firefly': 'fire-fly', 'worm': 'worm', 'snail': 'sn-ail', 'slug': 'sl-ug', 'spider': 'spi-der',
    'tick': 'tick', 'mite': 'mite', 'flea': 'fl-ea', 'mosquito': 'mos-qui-to', 'fly': 'fl-y',
};    
    // ===== PEOPLE & CHARACTERS =====
const w_people = {
    'king': 'k-ing', 'queen': 'qu-een', 'prince': 'prince', 'princess': 'prin-cess', 'knight': 'knight',
    'castle': 'cas-tle', 'tower': 'tow-er', 'moat': 'm-oat', 'dungeon': 'dun-geon', 'throne': 'thr-one',
    'crown': 'cr-own', 'scepter': 'scep-ter', 'royal': 'roy-al', 'palace': 'pal-ace', 'emperor': 'em-per-or',
    'empress': 'em-press', 'duke': 'd-uke', 'duchess': 'duch-ess', 'lord': 'lord', 'lady': 'la-dy',
    'squire': 's-quire', 'page': 'p-age', 'jester': 'jest-er', 'wizard': 'wiz-ard', 'witch': 'witch',
    'warlock': 'war-lock', 'sorcerer': 'sor-cer-er', 'sorceress': 'sor-cer-ess', 'dragon': 'drag-on',
    'unicorn': 'u-ni-corn', 'mermaid': 'mer-maid', 'fairy': 'fair-y', 'pixie': 'pix-ie', 'sprite': 'spr-ite',
    'elf': 'elf', 'elves': 'elves', 'dwarf': 'dwarf', 'gnome': 'gn-ome', 'ogre': 'o-gre',
    'giant': 'gi-ant', 'troll': 'troll', 'goblin': 'gob-lin', 'imp': 'imp', 'sprite': 'spr-ite',
    'ghost': 'gh-ost', 'skeleton': 'skel-e-ton', 'vampire': 'vam-pire', 'werewolf': 'were-wolf',
    'zombie': 'zom-bie', 'mummy': 'mum-my', 'monster': 'mon-ster', 'creature': 'crea-ture',
    'beast': 'beast', 'fiend': 'fi-end', 'demon': 'de-mon', 'devil': 'dev-il', 'angel': 'an-gel',
    'saint': 'saint', 'priest': 'pri-est', 'monk': 'monk', 'nun': 'nun', 'pilgrim': 'pil-grim',
    'shepherd': 'shep-herd', 'farmer': 'farm-er', 'peasant': 'peas-ant', 'villager': 'vil-lag-er',
    'merchant': 'mer-chant', 'trader': 'trad-er', 'craftsman': 'crafts-man', 'smith': 'smith',
    'weaver': 'weav-er', 'carpenter': 'car-pen-ter', 'mason': 'ma-son', 'tailor': 'tai-lor',
    'cobbler': 'cob-bler', 'butcher': 'butch-er', 'baker': 'bak-er', 'cook': 'c-oo-k',
    'chef': 'chef', 'scullion': 'scull-ion', 'servant': 'serv-ant', 'maid': 'm- aid', 'butler': 'but-ler',
    'squire': 's-quire', 'sailor': 'sail-or', 'pirate': 'pi-rate', 'captain': 'cap-tain', 'mate': 'm-ate',
    'bosun': 'bo-sun', 'crew': 'cr-ew', 'voyage': 'voy-age', 'explore': 'ex-plore', 'discover': 'dis-cov-er',
    'adventure': 'ad-ven-ture', 'quest': 'quest', 'journey': 'jour-ney', 'pilgrimage': 'pil-grim-age',
    'trek': 'trek', 'expedition': 'ex-pe-di-tion', 'safari': 'sa-fa-ri', 'hunt': 'hunt', 'hunter': 'hunt-er',
    'ranger': 'rang-er', 'scout': 'scout', 'guide': 'g-uide', 'tracker': 'track-er', 'pathfinder': 'path-find-er',
    
    // ===== ACTIONS & VERBS =====
    'run': 'r-un', 'jump': 'j-ump', 'hop': 'h-op', 'skip': 'sk-ip', 'leap': 'l-eap',
    'bound': 'b-ou-nd', 'spring': 'spr-ing', 'bounce': 'b-ou-nce', 'vault': 'vault', 'dive': 'd-ive',
    'swim': 'sw-im', 'wade': 'w-ade', 'paddle': 'pad-dle', 'splash': 'splash', 'spray': 'spr-ay',
    'float': 'fl-oat', 'sink': 's-ink', 'drift': 'dr-ift', 'glide': 'gl-ide', 'soar': 'soar',
    'fly': 'fl-y', 'flit': 'fl-it', 'flutter': 'flut-ter', 'hover': 'hov-er', 'swoop': 'sw-oop',
    'dive': 'd-ive', 'plunge': 'plunge', 'climb': 'cl-imb', 'scale': 'sc-ale', 'scramble': 'scram-ble',
    'crawl': 'cr-awl', 'creep': 'cr-eep', 'skulk': 'skulk', 'sneak': 'sn-eak', 'tiptoe': 'tip-toe',
    'walk': 'w-alk', 'stroll': 'st-roll', 'saunter': 'saun-ter', 'wander': 'w-and-er', 'roam': 'r-oam',
    'ramble': 'ram-ble', 'meander': 'me-an-der', 'stride': 'str-ide', 'march': 'm-arch', 'parade': 'pa-rade',
    'march': 'm-arch', 'stamp': 'stamp', 'stomp': 'st-omp', 'trample': 'tram-ple', 'tread': 'tr-ead',
    'trudge': 'trudge', 'plod': 'pl-od', 'slog': 'slog', 'toil': 't-oil', 'labor': 'la-bor',
    'work': 'w-or-k', 'drudge': 'dr-udge', 'slave': 'sl-ave', 'toil': 't-oil', 'strive': 'str-ive',
    'struggle': 'strug-gle', 'fight': 'f-ight', 'battle': 'batt-le', 'war': 'w-ar', 'combat': 'com-bat',
    'duel': 'd-uel', 'feud': 'f-eud', 'contest': 'con-test', 'compete': 'com-pete', 'oppose': 'op-pose',
    'resist': 're-sist', 'defend': 'de-fend', 'protect': 'pro-tect', 'guard': 'g-uard', 'shield': 'sh-ield',
    'shelter': 'shel-ter', 'harbor': 'har-bor', 'safeguard': 'safe-guard', 'preserve': 'pre-serve',
    'save': 's-ave', 'rescue': 'res-cue', 'liberate': 'lib-er-ate', 'free': 'fr-ee', 'release': 're-lease',
    'emancipate': 'e-man-ci-pate', 'redeem': 're-deem', 'ransom': 'ran-som', 'deliver': 'de-liv-er',
    'extricate': 'ex-tri-cate', 'disentangle': 'dis-en-tang-le', 'untangle': 'un-tang-le', 'unravel': 'un-rav-el',
    'unwind': 'un-wind', 'unfold': 'un-fold', 'uncover': 'un-cov-er', 'reveal': 're-veal', 'disclose': 'dis-close',
    'expose': 'ex-pose', 'betray': 'be-tray', 'manifest': 'man-i-fest', 'show': 'sh-ow', 'display': 'dis-play',
    'exhibit': 'ex-hib-it', 'present': 'pre-sent', 'offer': 'of-fer', 'proffer': 'prof-fer', 'provide': 'pro-vide',
    'supply': 'sup-ply', 'furnish': 'fur-nish', 'grant': 'grant', 'bestow': 'be-stow', 'impart': 'im-part',
    'confer': 'con-fer', 'award': 'a-ward', 'accord': 'ac-cord', 'vouchsafe': 'vouch-safe', 'yield': 'y-ield',
    'produce': 'pro-duce', 'bear': 'bear', 'generate': 'gen-er-ate', 'create': 'cre-ate', 'make': 'make',
    'form': 'f-orm', 'shape': 'sh-ape', 'fashion': 'fash-ion', 'forge': 'f-or-ge', 'fabricate': 'fab-ri-cate',
    'construct': 'con-struct', 'build': 'b-u-ild', 'erect': 'e-rect', 'raise': 'r- aise', 'rear': 're-ar',
    'assemble': 'as-sem-ble', 'manufacture': 'man-u-fac-ture', 'compose': 'com-pose', 'devise': 'de-vise',
    'invent': 'in-vent', 'originate': 'o-rig-i-nate', 'initiate': 'in-i-ti-ate', 'begin': 'be-gin', 'commence': 'com-mence',
    'start': 'st-art', 'embark': 'em-bark', 'launch': 'l-aunch', 'institute': 'in-sti-tute', 'establish': 'es-tab-lish',
    'found': 'f-ound', 'ground': 'gr-ound', 'base': 'b-ase', 'root': 'r-oot', 'embed': 'em-bed', 'implant': 'im-plant',
    'plant': 'pl-ant', 'sow': 's-ow', 'seed': 's-eed', 'grow': 'gr-ow', 'cultivate': 'cult-i-vate', 'raise': 'r- aise',
    'rear': 're-ar', 'nurture': 'nur-ture', 'foster': 'fos-ter', 'promote': 'pro-mote', 'advance': 'ad-vance',
    'further': 'fur-ther', 'forward': 'for-ward', 'hasten': 'hast-en', 'speed': 'sp-eed', 'quicken': 'quick-en',
    'accelerate': 'ac-cel-er-ate', 'expedite': 'ex-pe-dite', 'rush': 'r-ush', 'dash': 'd-ash', 'hurry': 'hur-ry',
    'scurry': 'scur-ry', 'scamper': 'scam-per', 'scuttle': 'scutt-le', 'scramble': 'scram-ble', 'hasten': 'hast-en',
    'hie': 'h-ie', 'hast': 'h-ast', 'posthaste': 'post-haste', 'breakneck': 'break-neck', 'precipitate': 'pre-cip-i-tate',
    'sudden': 'sud-den', 'abrupt': 'ab-rupt', 'precipitous': 'pre-cip-i-tous', 'steep': 'st-eep', 'sheer': 'sh-eer',
    'perpendicular': 'per-pen-dic-u-lar', 'vertical': 'ver-ti-cal', 'plumb': 'plumb', 'upright': 'up-r-ight',
    'erect': 'e-rect', 'standing': 'stand-ing', 'upstanding': 'up-stand-ing', 'prone': 'pr-one', 'prostrate': 'pros-trate',
    'recumbent': 're-cumb-ent', 'supine': 'su-pine', 'horizontal': 'hor-i-zon-tal', 'flat': 'fl-at', 'level': 'lev-el',
    'even': 'ev-en', 'smooth': 'smooth', 'plane': 'pl-ane', 'flush': 'flush', 'aligned': 'a-ligned',
    'true': 'tr-ue', 'straight': 'str- aight', 'direct': 'di-rect', 'linear': 'lin-ear', 'rectilinear': 'rec-ti-lin-ear',
    'curved': 'curv-ed', 'crooked': 'crook-ed', 'bent': 'b-ent', 'twisted': 'twist-ed', 'tortuous': 'tor-tu-ous',
    'winding': 'wind-ing', 'serpentine': 'ser-pen-tine', 'meandering': 'me-and-er-ing', 'flexuous': 'flex-u-ous',
    'undulating': 'un-du-lat-ing', 'sinuous': 'sin-u-ous', 'convoluted': 'con-vo-lut-ed', 'labyrinthine': 'lab-y-rinth-ine',
    'mazelike': 'maze-like', 'complex': 'com-plex', 'complicated': 'com-pli-cat-ed', 'intricate': 'in-tri-cate',
    'involved': 'in-volv-ed', 'elaborate': 'e-lab-o-rate', 'detailed': 'de-tailed', 'ornate': 'or-nate',
    'embellished': 'em-bell-ished', 'adorned': 'a-dorn-ed', 'decorated': 'dec-o-rat-ed', 'bejeweled': 'be-jew-eled',
    'gemstone': 'gem-st-one', 'jewel': 'jew-el', 'crown': 'cr-own', 'tiara': 'ti-a-ra', 'scepter': 'scep-ter',
    'orb': 'orb', 'robe': 'r-obe', 'mantle': 'man-tle', 'cloak': 'cl-oak', 'cape': 'c-ape', 'gown': 'g-own',
    'dress': 'dress', 'garment': 'gar-ment', 'attire': 'at-tire', 'apparel': 'ap-par-el', 'raiment': 'raiment',
    'vesture': 'ves-ture', 'habiliment': 'ha-bil-i-ment', 'accoutrement': 'ac-cou-tre-ment', 'accessory': 'ac-ces-so-ry',
    'adornment': 'a-dorn-ment', 'ornament': 'or-na-ment', 'decoration': 'dec-o-ra-tion', 'embellishment': 'em-bell-ish-ment',
    'frill': 'fr-ill', 'furbelow': 'fur-be-low', 'flounce': 'fl-ounce', 'ruffle': 'ruf-fle', 'trimmings': 'trim-mings',
    'finery': 'fin-er-y', 'regalia': 're-ga-li-a', 'insignia': 'in-sig-ni-a', 'badge': 'b-ad-ge', 'medal': 'med-al',
    'ribbon': 'rib-bon', 'rosette': 'ro-sette', 'laurel': 'laur-el', 'wreath': 'wr-eath', 'garland': 'gar-land',
    'festoon': 'fes-toon', 'bunting': 'bunt-ing', 'pennant': 'pen-nant', 'banner': 'ban-ner', 'flag': 'flag',
    'standard': 'stand-ard', 'colors': 'col-ors', 'streamer': 'stream-er', 'banderole': 'ban-der-ole',
    'oriflamme': 'or-i-flamme', 'gonfalon': 'gon-fa-lon', 'jack': 'j-ack', 'ensign': 'en-sign', 'pennon': 'pen-non',
    'broad': 'br-oad', 'narrow': 'nar-row', 'wide': 'w-ide', 'vast': 'v-ast', 'immense': 'im-mense',
    'enormous': 'e-nor-mous', 'giant': 'gi-ant', 'huge': 'h-uge', 'massive': 'mass-ive', 'colossal': 'co-loss-al',
    'gargantuan': 'gar-gan-tu-an', 'titanic': 'ti-tan-ic', 'elephantine': 'el-e-phan-tine', 'mammoth': 'mam-moth',
    'behemoth': 'be-he-moth', 'leviathan': 'le-vi-a-than', 'cyclopean': 'cy-clo-pe-an', 'brobdingnagian': 'brob-ding-nag-i-an',
    'lilliputian': 'lil-li-pu-tian', 'tiny': 't-iny', 'minute': 'min-ute', 'microscopic': 'mi-cro-scop-ic',
    'infinitesimal': 'in-fin-i-tes-i-mal', 'diminutive': 'di-min-u-tive', 'miniature': 'min-i-a-ture',
    'petite': 'pe-tite', 'weeny': 'ween-y', 'teensy': 'teens-y', 'itsy-bitsy': 'it-sy-bit-sy', 'teeny-weeny': 'tee-ny-ween-y',
    'bitsy': 'bit-sy', 'puny': 'p-uny', 'pint-sized': 'pint-sized', 'pocket-sized': 'pock-et-sized',
    'fun-sized': 'fun-sized', 'bite-sized': 'bite-sized', 'compact': 'com-pact', 'portable': 'port-a-ble',
    'handheld': 'hand-held', 'lap-sized': 'lap-sized', 'vest-pocket': 'vest-pock-et', 'palm-sized': 'palm-sized',
    'wallet-sized': 'wall-et-sized', 'credit-card-sized': 'cred-it-card-sized', 'micro': 'mi-cro', 'nano': 'nan-o',
    'pico': 'pi-co', 'femto': 'fem-to', 'atto': 'at-to', 'zepto': 'zep-to', 'yocto': 'yoc-to',
    'kilo': 'kil-o', 'mega': 'meg-a', 'giga': 'gig-a', 'tera': 'ter-a', 'peta': 'pet-a',
    'exa': 'ex-a', 'zetta': 'zet-ta', 'yotta': 'yot-ta', 'metric': 'met-ric', 'imperial': 'im-pe-ri-al',
    'customary': 'cus-tom-ar-y', 'standard': 'stand-ard', 'conventional': 'con-ven-tion-al', 'traditional': 'tra-di-tion-al',
    'customary': 'cus-tom-ar-y', 'habitual': 'hab-it-u-al', 'usual': 'u-su-al', 'normal': 'nor-mal',
    'regular': 'reg-u-lar', 'routine': 'rou-tine', 'typical': 'typ-i-cal', 'common': 'com-mon',
    'ordinary': 'or-di-nar-y', 'mundane': 'mun-dane', 'quotidian': 'quo-tid-i-an', 'everyday': 'ev-ery-day',
    'workaday': 'work-a-day', 'prosaic': 'pro-sa-ic', 'pedestrian': 'pe-des-tri-an', 'humdrum': 'hum-drum',
    'tedious': 'te-di-ous', 'tiresome': 'tire-some', 'wearisome': 'weary-some', 'stodgy': 'stodg-y',
    'dull': 'dull', 'boring': 'bor-ing', 'uninteresting': 'un-in-ter-est-ing', 'dreary': 'dreary',
    'gloomy': 'gloom-y', 'somber': 'som-ber', 'sullen': 'sull-en', 'morose': 'mo-rose', 'glum': 'gl-um',
    'mournful': 'mourn-ful', 'lugubrious': 'lu-gu-bri-ous', 'melancholy': 'mel-an-chol-y',
    'sorrowful': 'sor-row-ful', 'dolorous': 'dol-or-ous', 'plaintive': 'plain-tive', 'rueful': 'rue-ful',
    'regretful': 're-gret-ful', 'remorseful': 're-morse-ful', 'contrite': 'con-trite', 'penitent': 'pen-i-tent',
    'repentant': 're-pent-ant', 'apologetic': 'a-pol-o-get-ic', 'forgive': 'for-give', 'forgave': 'for-gave',
    'forgiven': 'for-giv-en', 'forgiving': 'for-giv-ing', 'forgiveness': 'for-give-ness', 'pardon': 'par-don',
    'pardonable': 'par-don-a-ble', 'excusable': 'ex-cus-a-ble', 'justifiable': 'jus-ti-fi-a-ble',
    'defensible': 'de-fens-i-ble', 'venial': 'ven-i-al', 'minor': 'mi-nor', 'slight': 'sl-ight', 'petty': 'pet-ty',
    'trifling': 'tri-fl-ing', 'inconsequential': 'in-con-se-quen-tial', 'negligible': 'neg-li-gi-ble',
    'insignificant': 'in-sig-nif-i-cant', 'paltry': 'palt-ry', 'meager': 'mea-ger', 'scant': 'sc-ant',
    'scanty': 'scant-y', 'sparse': 'sparse', 'skimpy': 'skimp-y', 'scrimpy': 'scrimp-y', 'piddling': 'pidd-ling',
    'piffling': 'piff-ling', 'measly': 'meas-ly', 'pitiful': 'pit-i-ful', 'pathetic': 'pa-thet-ic',
    'lamentable': 'la-men-ta-ble', 'deplorable': 'de-plor-a-ble', 'wretched': 'wretch-ed', 'miserable': 'mis-er-a-ble',
    'dismal': 'dis-mal', 'abysmal': 'a-bys-mal', 'atrocious': 'a-tro-cious', 'execrable': 'ex-ec-ra-ble',
    'abominable': 'a-bom-i-na-ble', 'odious': 'o-di-ous', 'repugnant': 're-pug-nant', 'repulsive': 're-pul-sive',
    'revolting': 're-volt-ing', 'disgusting': 'dis-gust-ing', 'nauseating': 'nau-se-at-ing', 'sickening': 'sick-en-ing',
    'loathsome': 'loath-some', 'detestable': 'de-test-a-ble', 'hateful': 'hate-ful', 'abhorrent': 'ab-hor-rent',
    'despicable': 'des-pic-a-ble', 'contemptible': 'con-temp-ti-ble', 'mean': 'm-ean', 'base': 'b-ase',
    'vile': 'v-ile', 'foul': 'f-oul', 'filthy': 'fil-thy', 'squalid': 'squal-id', 'sordid': 'sor-did',
    'seedy': 'seed-y', 'sleazy': 'slea-zy', 'tawdry': 'taw-dry', 'cheap': 'ch-eap', 'shoddy': 'shod-dy',
    'trashy': 'trash-y', 'rubbishy': 'rub-bish-y', 'junky': 'junk-y', 'garbage': 'gar-bage', 'waste': 'w-aste',
    'refuse': 're-fuse', 'litter': 'litt-er', 'debris': 'deb-ris', 'detritus': 'de-tri-tus', 'dregs': 'dregs',
    'scum': 'scum', 'dross': 'dross', 'chaff': 'chaff', 'husk': 'h-usk', 'shell': 'shell', 'peel': 'p-eel',
    'rind': 'r-ind', 'skin': 'sk-in', 'crust': 'cr-ust', 'crumb': 'cr-umb', 'fragment': 'frag-ment',
    'shard': 'sh-ard', 'sliver': 'sliv-er', 'splinter': 'splint-er', 'shred': 'sh-red', 'snippet': 'snip-pet',
    'scrap': 'scr-ap', 'bit': 'b-it', 'piece': 'p-iece', 'portion': 'por-tion', 'part': 'p-art', 'segment': 'seg-ment',
    'section': 'sec-tion', 'sector': 'sec-tor', 'division': 'di-vi-sion', 'subdivision': 'sub-di-vi-sion',
    'department': 'de-part-ment', 'branch': 'branch', 'wing': 'w-ing', 'arm': 'arm', 'offshoot': 'off-shoot',
    'extension': 'ex-ten-sion', 'annex': 'an-nex', 'appendage': 'ap-pend-age', 'addition': 'ad-di-tion',
    'supplement': 'sup-ple-ment', 'appendix': 'ap-pend-ix', 'adjunct': 'ad-junct', 'accessory': 'ac-ces-so-ry',
    'attachment': 'at-tach-ment', 'affiliation': 'af-fil-i-a-tion', 'association': 'as-so-ci-a-tion',
    'alliance': 'al-li-ance', 'coalition': 'co-a-l-i-tion', 'federation': 'fed-er-a-tion', 'confederation': 'con-fed-er-a-tion',
    'union': 'un-ion', 'league': 'l-eague', 'confederacy': 'con-fed-er-a-cy', 'consortium': 'con-sor-ti-um',
    'syndicate': 'syn-di-cate', 'cartel': 'car-tel', 'trust': 'trust', 'combine': 'com-bine', 'pool': 'p-ool',
    'cooperative': 'co-op-er-a-tive', 'collective': 'col-lect-ive', 'commune': 'com-mune', 'community': 'com-mun-i-ty',
    'society': 'so-ci-e-ty', 'association': 'as-so-ci-a-tion', 'organization': 'or-gan-i-za-tion', 'institution': 'in-sti-tu-tion',
    'establishment': 'es-tab-lish-ment', 'foundation': 'foun-da-tion', 'corporation': 'cor-por-a-tion', 'company': 'com-pa-ny',
    'firm': 'f-irm', 'enterprise': 'en-ter-prise', 'venture': 'ven-ture', 'operation': 'op-er-a-tion', 'concern': 'con-cern',
    'outfit': 'out-fit', 'setup': 'set-up', 'arrangement': 'ar-range-ment', 'configuration': 'con-fig-u-ra-tion',
    'formation': 'for-ma-tion', 'structure': 'struc-ture', 'framework': 'frame-work', 'skeleton': 'skel-e-ton',
    'scaffold': 'scaf-fold', 'scaffolding': 'scaf-fold-ing', 'framework': 'frame-work', 'shell': 'shell',
    'husk': 'h-usk', 'crust': 'cr-ust', 'coating': 'co-at-ing', 'covering': 'cov-er-ing', 'layer': 'lay-er',
    'stratum': 'stra-tum', 'sheet': 'sh-eet', 'film': 'f-ilm', 'membrane': 'mem-brane', 'skin': 'sk-in',
    'hide': 'h-ide', 'pelt': 'pelt', 'fur': 'fur', 'fleece': 'fl-eece', 'wool': 'w-ool', 'down': 'down',
    'feather': 'feath-er', 'plumage': 'plum-age', 'scale': 'sc-ale', 'scute': 'scute', 'scute': 'scute',
    'scute': 'scute', 'scute': 'scute',
};
    // ===== PLACES & SETTINGS =====
const w_places = {
    'forest': 'for-est', 
    'woods': 'w-oo-ds', 
    'jungle': 'jun-gle', 
    'rainforest': 'r-ain-for-est', 
    'taiga': 'tai-ga',
    'savanna': 'sa-van-na', 'prairie': 'pr-air-ie', 'steppe': 'step-pe', 'pampas': 'pam-pas', 'veldt': 've-l-dt',
    'tundra': 'tun-dra', 'desert': 'des-ert', 'sahara': 'sa-har-a', 'gobi': 'go-bi', 'arctic': 'arc-tic',
    'antarctic': 'ant-arc-tic', 'polar': 'po-lar', 'region': 're-gion', 'zone': 'z-one', 'area': 'ar-ea',
    'territory': 'ter-ri-to-ry', 'domain': 'do-main', 'realm': 'realm', 'kingdom': 'k-ing-dom', 'empire': 'em-p-ire',
    'country': 'coun-try', 'nation': 'na-tion', 'state': 'st-ate', 'province': 'pr-ov-ince', 'county': 'coun-ty',
    'city': 'c-i-ty', 'town': 't-own', 'village': 'v-ill-age', 'hamlet': 'ham-let', 'settlement': 'set-tle-ment',
    'outpost': 'out-p-ost', 'fort': 'f-ort', 'castle': 'cas-tle', 'palace': 'pal-ace', 'tower': 'tow-er',
    'dungeon': 'dun-ge-on', 'keep': 'k-ee-p', 'moat': 'm-oat', 'drawbridge': 'dr-aw-br-idge', 'gatehouse': 'g-ate-hou-se',
    'bastion': 'bas-tion', 'rampart': 'ram-part', 'wall': 'w-all', 'fortress': 'for-tress', 'citadel': 'cit-a-del',
    'stronghold': 'st-rong-hold', 'fastness': 'fast-ness', 'redoubt': 're-doubt', 'blockhouse': 'block-house',
    'outwork': 'out-wo-rk', 'parapet': 'par-a-pet', 'bulwark': 'bul-w-ark', 'embankment': 'em-b-ank-m-ent', 'palisade': 'pal-is-ade',
    'stock': 'st-ock','stockade': 'st-ock-ade', 'barricade': 'bar-ri-cade', 'barrier': 'bar-ri-er', 'obstacle': 'ob-sta-cle',
    'hindrance': 'hin-drance', 'impediment': 'im-ped-i-ment', 'obstruction': 'ob-struct-ion', 'blockage': 'block-age',
    'stoppage': 'st-op-pa-ge', 'jam': 'j-am', 'clog': 'cl-og', 'bottleneck': 'bot-tle-neck', 'gridlock': 'grid-lock',
    'deadlock': 'dead-lock', 'stand': 'st-and','standstill': 'st-and-s-till', 'halt': 'h- alt', 'stop': 'st-op', 'cease': 'c-ease',
    'terminate': 'ter-min-ate', 'end': 'end', 'finish': 'fin-ish', 'conclude': 'con-clude', 'complete': 'com-plete',
    'fulfill': 'ful-fill', 'accomplish': 'ac-com-pl-ish', 'achieve': 'a-chi-eve', 'attain': 'att-ain', 'reach': 'r-each',
    'gain': 'g-ain', 'secure': 'se-cure', 'obtain': 'ob-tain', 'procure': 'pro-cure', 'acquire': 'ac-qu-ire',
    'get': 'get', 'receive': 're-ce-ive', 'accept': 'ac-ce-pt', 'take': 't-ake', 'adopt': 'ad-opt',
    'assume': 'as-sume', 'undertake': 'un-der-take', 'shoulder': 'sh-oul-der', 'bear': 'bear', 'carry': 'carr-y',
    'transport': 'tr-ans-p-ort', 'convey': 'con-vey', 'transmit': 'tr-ans-mit', 'transfer': 'tr-ans-fer', 'deliver': 'de-liv-er',
    'dispatch': 'dis-patch', 'send': 's-end', 'ship': 'sh-ip', 'haul': 'h-aul', 'drag': 'dr-ag', 'pull': 'p-ull',
    'tug': 't-ug', 'tow': 't-ow', 'draw': 'dr-aw', 'haul': 'h-au-l', 'lug': 'l-ug', 'heave': 'h-ea-ve',
    'hoist': 'hoist', 'elevate': 'el-ev-ate', 'raise': 'r- aise', 'lift': 'l-ift', 'boost': 'boost',
    'upraise': 'up-ra-ise', 'upheave': 'up-h-eave', 'upthrust': 'up-thr-ust', 'hoist': 'ho-ist', 'heft': 'h-eft',
    'heave': 'heave', 'uphold': 'up-hold', 'support': 'sup-port', 'sustain': 'sus-tain', 'maintain': 'main-tain',
    'prop': 'prop', 'brace': 'br-ace', 'buttress': 'but-tress', 'shore': 'sh-ore', 'underpin': 'un-der-pin',
    'undergird': 'un-der-gird', 'underprop': 'un-der-prop', 'underbrace': 'un-der-brace', 'underlie': 'un-der-lie',
    'underlay': 'un-der-lay', 'underpinning': 'un-der-pin-ning', 'foundation': 'fou-nd-a-tion', 'basis': 'b-a-sis',
    'groundwork': 'ground-work', 'substratum': 'sub-s-tra-tum', 'understructure': 'un-der-str-uc-ture', 'substructure': 'sub-struc-ture',
    'infrastructure': 'in-fra-str-uc-ture', 'framework': 'fr-ame-work', 'skeleton': 'skel-e-ton', 'scaffold': 'scaf-fold',
    'scaffolding': 'scaf-fold-ing', 'supporting': 'sup-po-rt-ing', 'reinforcement': 're-in-force-ment', 'strengthening': 'strength-en-ing',
    'augmentation': 'aug-men-ta-tion', 'supplementation': 'sup-ple-men-ta-tion', 'addition': 'ad-di-tion', 'extension': 'ex-ten-sion',
    'expansion': 'ex-pan-sion', 'enlargement': 'en-large-ment', 'increase': 'in-crease', 'growth': 'growth',
    'development': 'de-vel-op-ment', 'evolution': 'ev-o-lu-tion', 'progression': 'pro-gres-sion', 'advancement': 'ad-vance-ment',
    'progress': 'pro-gress', 'headway': 'head-way', 'breakthrough': 'break-through', 'improvement': 'im-prove-ment',
    'enhancement': 'en-hance-ment', 'amelioration': 'a-me-li-o-ra-tion', 'betterment': 'bet-ter-ment', 'refinement': 're-fine-ment',
    'polish': 'pol-ish', 'perfection': 'per-fec-tion', 'culmination': 'cul-min-a-tion', 'consummation': 'con-summ-a-tion',
    'realization': 're-al-i-za-tion', 'actualization': 'ac-tu-al-i-za-tion', 'materialization': 'ma-te-ri-al-i-za-tion',
    'fulfillment': 'ful-fill-ment', 'achievement': 'a-chieve-ment', 'accomplishment': 'ac-com-plish-ment',
    'attainment': 'at-tain-ment', 'acquisition': 'ac-qui-si-tion', 'procurement': 'pro-cure-ment', 'procuring': 'pro-cur-ing',
    'obtaining': 'ob-tain-ing', 'gaining': 'gain-ing', 'winning': 'win-ning', 'earning': 'earn-ing', 'securing': 'se-cur-ing',
    'capturing': 'cap-tur-ing', 'catching': 'catch-ing', 'seizing': 'seiz-ing', 'grasping': 'grasp-ing', 'clutching': 'clutch-ing',
    'snatching': 'snatch-ing', 'grabbing': 'grab-bing', 'taking': 't-ak-ing', 'receiving': 're-ceiv-ing', 'accepting': 'ac-cept-ing',
    'admitting': 'ad-mitt-ing', 'acknowledging': 'ac-knowl-edg-ing', 'conceding': 'con-ced-ing', 'allowing': 'al-low-ing',
    'permitting': 'per-mitt-ing', 'authorizing': 'auth-o-riz-ing', 'sanctioning': 'sanc-tion-ing', 'approving': 'ap-prov-ing',
    'endorsing': 'en-dors-ing', 'ratifying': 'rat-i-fy-ing', 'confirming': 'con-firm-ing', 'validating': 'val-i-dat-ing',
    'verifying': 'ver-i-fy-ing', 'substantiating': 'sub-stan-ti-at-ing', 'corroborating': 'cor-rob-o-rat-ing',
    'authenticating': 'au-then-ti-cat-ing', 'legalizing': 'le-gal-iz-ing', 'legitimizing': 'le-git-i-miz-ing',
    'warranting': 'war-rant-ing', 'justifying': 'jus-ti-fy-ing', 'vindicating': 'vin-di-cat-ing', 'defending': 'de-fend-ing',
    'protecting': 'pro-tect-ing', 'shielding': 'shield-ing', 'guarding': 'g-uard-ing', 'safeguarding': 'safe-guard-ing',
    'preserving': 'pre-serv-ing', 'conserving': 'con-serv-ing', 'maintaining': 'main-tain-ing', 'sustaining': 'sus-tain-ing',
    'upholding': 'up-hold-ing', 'supporting': 'sup-port-ing', 'backing': 'back-ing', 'advocating': 'ad-vo-cat-ing',
    'championing': 'cham-pi-on-ing', 'espousing': 'es-pous-ing', 'embracing': 'em-brac-ing', 'adopting': 'a-dopt-ing',
    'accepting': 'ac-cept-ing', 'receiving': 're-ceiv-ing', 'welcoming': 'wel-com-ing', 'hospitality': 'hos-pi-tal-i-ty',
    'generosity': 'gen-er-os-i-ty', 'kindness': 'kind-ness', 'compassion': 'com-pas-sion', 'sympathy': 'sym-pa-thy',
    'empathy': 'em-pa-thy', 'understanding': 'un-der-stand-ing', 'patience': 'pa-tience', 'tolerance': 'tol-er-ance',
    'forbearance': 'for-bear-ance', 'leniency': 'le-ni-en-cy', 'indulgence': 'in-dul-gence', 'permissiveness': 'per-mis-sive-ness',
    'liberality': 'lib-er-al-i-ty', 'open-mindedness': 'o-pen-mind-ed-ness', 'broad-mindedness': 'broad-mind-ed-ness',
    'tolerance': 'tol-er-ance', 'acceptance': 'ac-cept-ance', 'inclusiveness': 'in-clu-sive-ness', 'diversity': 'di-ver-si-ty',
    'variety': 'va-ri-e-ty', 'multifariousness': 'mul-ti-far-i-ous-ness', 'heterogeneity': 'het-er-o-ge-ne-i-ty',
    'miscellany': 'mis-cel-la-ny', 'medley': 'med-ley', 'mixture': 'mix-ture', 'amalgam': 'a-mal-gam', 'blend': 'bl-end',
    'fusion': 'fu-sion', 'synthesis': 'syn-the-sis', 'composite': 'com-pos-ite', 'compound': 'com-pound', 'concoction': 'con-coc-tion',
    'brew': 'br-ew', 'potation': 'po-ta-tion', 'potion': 'po-tion', 'elixir': 'e-lix-ir', 'tonic': 'ton-ic', 'draught': 'dr-aught',
    'dose': 'd-ose', 'medicine': 'med-i-cine', 'remedy': 'rem-e-dy', 'cure': 'c-ur-e', 'antidote': 'an-ti-dote',
    'panacea': 'pan-a-ce-a', 'nostrum': 'nos-trum', 'physic': 'phys-ic', 'drug': 'dr-ug', 'pharmaceutical': 'phar-ma-ceu-ti-cal',
    'medicament': 'me-dic-a-ment', 'salve': 's-al-ve', 'ointment': 'oint-ment', 'lotion': 'l-otion', 'balm': 'b-alm',
    'unguent': 'un-guent', 'emollient': 'e-mol-li-ent', 'liniment': 'lin-i-ment', 'poultice': 'poul-tice',
    'compress': 'com-press', 'bandage': 'band-age', 'dressing': 'dress-ing', 'plaster': 'plas-ter', 'cast': 'c-ast',
    'splint': 'splint', 'sling': 'sling', 'crutch': 'cr-utch', 'wheelchair': 'wheel-chair', 'stretcher': 'stretch-er',
    'litter': 'litt-er', 'gurney': 'gur-ney', 'bed': 'b-ed', 'cot': 'cot', 'mattress': 'matt-ress', 'pillow': 'pil-low',
    'blanket': 'blank-et', 'sheet': 'sh-eet', 'cover': 'cov-er', 'quilt': 'quilt', 'comforter': 'com-fort-er',
    'duvet': 'du-vet', 'bedspread': 'b-ed-spread', 'canopy': 'can-o-py', 'baldachin': 'bal-da-chin', 'tester': 'test-er',
    'marquee': 'mar-quee', 'awning': 'awn-ing', 'tent': 'tent', 'pavilion': 'pa-vil-ion', 'tabernacle': 'tab-er-na-cle',
    'shrine': 'shrine', 'sanctuary': 'sanc-tu-a-ry', 'chapel': 'chap-el', 'oratory': 'or-a-tory', 'basilica': 'ba-sil-i-ca',
    'cathedral': 'ca-the-dral', 'church': 'ch-urch', 'temple': 'tem-ple', 'mosque': 'mosque', 'synagogue': 'syn-a-gogue',
    'pagoda': 'pa-go-da', 'monastery': 'mon-as-tery', 'convent': 'con-vent', 'abbey': 'ab-bey', 'priory': 'pri-o-ry',
    'hermitage': 'her-mit-age', 'cloister': 'clois-ter', 'refectory': 're-fec-to-ry', 'dormitory': 'dor-mi-to-ry',
    'cell': 'c-ell', 'hospice': 'hos-pice', 'infirmary': 'in-fir-ma-ry', 'hospital': 'hos-pi-tal', 'clinic': 'clin-ic',
    'surgery': 'sur-ger-y', 'pharmacy': 'phar-ma-cy', 'dispensary': 'dis-pen-sa-ry', 'apothecary': 'a-poth-e-car-y',
    'laboratory': 'lab-o-ra-to-ry', 'infirmary': 'in-fir-ma-ry', 'asylum': 'a-sy-lum', 'sanatorium': 'san-a-to-ri-um',
    'spa': 'spa', 'resort': 're-sort', 'retreat': 're-treat', 'sanctuary': 'sanc-tu-a-ry', 'haven': 'hav-en',
    'refuge': 'ref-uge', 'shelter': 'shel-ter', 'asylum': 'a-sy-lum', 'harbor': 'har-bor', 'port': 'p-ort',
    'haven': 'hav-en', 'oasis': 'o-a-sis', 'sanctuary': 'sanc-tu-a-ry', 'preserve': 'pre-serve', 'reserve': 're-serve',
    'conservancy': 'con-serv-an-cy', 'park': 'p-ark', 'garden': 'gar-den', 'zoo': 'zoo', 'menagerie': 'me-nag-er-ie',
    'preserve': 'pre-serve', 'reserve': 're-serve', 'sanctuary': 'sanc-tu-a-ry', 'refuge': 'ref-uge', 'shelter': 'shel-ter',
    'haven': 'hav-en', 'asylum': 'a-sy-lum', 'harbor': 'har-bor', 'port': 'p-ort', 'haven': 'hav-en', 'oasis': 'o-a-sis',
    'preserve': 'pre-serve', 'reserve': 're-serve', 'sanctuary': 'sanc-tu-a-ry', 'refuge': 'ref-uge', 'shelter': 'shel-ter',
    'haven': 'hav-en', 'asylum': 'a-sy-lum', 'harbor': 'har-bor', 'port': 'p-ort', 'haven': 'hav-en', 'oasis': 'o-a-sis',
    'preserve': 'pre-serve', 'reserve': 're-serve', 'sanctuary': 'sanc-tu-a-ry', 'refuge': 'ref-uge', 'shelter': 'shel-ter',
    'haven': 'hav-en', 'asylum': 'a-sy-lum', 'harbor': 'har-bor', 'port': 'p-ort', 'haven': 'hav-en', 'oasis': 'o-a-sis',
    'preserve': 'pre-serve', 'reserve': 're-serve', 'sanctuary': 'sanc-tu-a-ry', 'refuge': 'ref-uge', 'shelter': 'shel-ter',
    'haven': 'hav-en', 'asylum': 'a-sy-lum', 'harbor': 'har-bor', 'port': 'p-ort', 'haven': 'hav-en', 'oasis': 'o-a-sis',
    'preserve': 'pre-serve'
};

const storyWordSplits = [
    {name: 'sight_words', value: w_sight_words},
    {name: 'cvc_words', value: w_cvc_words},
    {name: 'blends_digraphs', value: w_blends_digraphs},
    {name: 'long_vowels', value: w_long_vowels},
    {name: 'vowel_teams', value: w_vowel_teams},
    {name: 'r_controlled_vowels', value: w_r_controlled_vowels},
    {name: 'multisyllabic_split', value: w_multisyllabic_split},
    {name: 'animals', value: w_animals},
    {name: 'nature', value: w_nature},
    {name: 'people', value: w_people},
    {name: 'places', value: w_places},
];